// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	public "ai-roleplay/services/character/api/internal/handler/public"
	"ai-roleplay/services/character/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建自定义角色
				Method:  http.MethodPost,
				Path:    "/api/character",
				Handler: public.CreateCharacterHandler(serverCtx),
			},
			{
				// 获取角色详情
				Method:  http.MethodGet,
				Path:    "/api/character/:id",
				Handler: public.GetCharacterDetailHandler(serverCtx),
			},
			{
				// 更新角色基本信息
				Method:  http.MethodPut,
				Path:    "/api/character/:id",
				Handler: public.UpdateCharacterHandler(serverCtx),
			},
			{
				// 删除角色
				Method:  http.MethodDelete,
				Path:    "/api/character/:id",
				Handler: public.DeleteCharacterHandler(serverCtx),
			},
			{
				// 收藏/取消收藏角色
				Method:  http.MethodPost,
				Path:    "/api/character/:id/favorite",
				Handler: public.ToggleFavoriteHandler(serverCtx),
			},
			{
				// 更新角色性格设置
				Method:  http.MethodPut,
				Path:    "/api/character/:id/personality",
				Handler: public.UpdatePersonalityHandler(serverCtx),
			},
			{
				// 更新角色提示词
				Method:  http.MethodPut,
				Path:    "/api/character/:id/prompt",
				Handler: public.UpdatePromptHandler(serverCtx),
			},
			{
				// 更新语音设置
				Method:  http.MethodPut,
				Path:    "/api/character/:id/voice",
				Handler: public.UpdateVoiceSettingsHandler(serverCtx),
			},
			{
				// 获取角色分类
				Method:  http.MethodGet,
				Path:    "/api/character/categories",
				Handler: public.GetCharacterCategoriesHandler(serverCtx),
			},
			{
				// 获取我的收藏角色
				Method:  http.MethodGet,
				Path:    "/api/character/favorites",
				Handler: public.GetMyFavoritesHandler(serverCtx),
			},
			{
				// 获取角色列表
				Method:  http.MethodGet,
				Path:    "/api/character/list",
				Handler: public.GetCharacterListHandler(serverCtx),
			},
			{
				// 获取我创建的角色
				Method:  http.MethodGet,
				Path:    "/api/character/my",
				Handler: public.GetMyCharactersHandler(serverCtx),
			},
			{
				// 获取热门角色
				Method:  http.MethodGet,
				Path:    "/api/character/popular",
				Handler: public.GetPopularCharactersHandler(serverCtx),
			},
			{
				// 获取推荐角色
				Method:  http.MethodGet,
				Path:    "/api/character/recommended",
				Handler: public.GetRecommendedCharactersHandler(serverCtx),
			},
			{
				// 搜索角色
				Method:  http.MethodGet,
				Path:    "/api/character/search",
				Handler: public.SearchCharactersHandler(serverCtx),
			},
			{
				// 获取角色标签
				Method:  http.MethodGet,
				Path:    "/api/character/tags",
				Handler: public.GetCharacterTagsHandler(serverCtx),
			},
		},
	)
}
