// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	chat "ai-roleplay/services/chat/api/internal/handler/chat"
	"ai-roleplay/services/chat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 侧边栏历史
				Method:  http.MethodGet,
				Path:    "/api/chat/before",
				Handler: chat.ChatHistoryBeforeHandler(serverCtx),
			},
			{
				// 创建新对话
				Method:  http.MethodPost,
				Path:    "/api/chat/conversation",
				Handler: chat.CreateConversationHandler(serverCtx),
			},
			{
				// 获取对话详情
				Method:  http.MethodGet,
				Path:    "/api/chat/conversation/:id",
				Handler: chat.GetConversationHandler(serverCtx),
			},
			{
				// 删除对话
				Method:  http.MethodDelete,
				Path:    "/api/chat/conversation/:id",
				Handler: chat.DeleteConversationHandler(serverCtx),
			},
			{
				// 导出对话记录
				Method:  http.MethodGet,
				Path:    "/api/chat/conversation/:id/export",
				Handler: chat.ExportConversationHandler(serverCtx),
			},
			{
				// 清空对话消息
				Method:  http.MethodDelete,
				Path:    "/api/chat/conversation/:id/messages",
				Handler: chat.ClearMessagesHandler(serverCtx),
			},
			{
				// 更新对话标题
				Method:  http.MethodPut,
				Path:    "/api/chat/conversation/:id/title",
				Handler: chat.UpdateConversationTitleHandler(serverCtx),
			},
			{
				// 获取对话列表
				Method:  http.MethodGet,
				Path:    "/api/chat/conversations",
				Handler: chat.GetConversationListHandler(serverCtx),
			},
			{
				// 批量删除对话
				Method:  http.MethodPost,
				Path:    "/api/chat/conversations/batch-delete",
				Handler: chat.BatchDeleteConversationsHandler(serverCtx),
			},
			{
				// 获取对话历史
				Method:  http.MethodPost,
				Path:    "/api/chat/history",
				Handler: chat.GetConversationHistoryHandler(serverCtx),
			},
			{
				// 发送消息
				Method:  http.MethodPost,
				Path:    "/api/chat/message",
				Handler: chat.SendMessageHandler(serverCtx),
			},
			{
				// 获取对话消息历史
				Method:  http.MethodGet,
				Path:    "/api/chat/messages",
				Handler: chat.GetMessagesHandler(serverCtx),
			},
			{
				// 搜索对话
				Method:  http.MethodGet,
				Path:    "/api/chat/search",
				Handler: chat.SearchConversationsHandler(serverCtx),
			},
			{
				// 发送消息并获取SSE流式响应
				Method:  http.MethodGet,
				Path:    "/api/chat/send",
				Handler: chat.ChatSendHandler(serverCtx),
			},
		},
	)
}
