// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"ai-roleplay/services/speech/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthCheckHandler(serverCtx),
			},
			{
				// 语音转文字
				Method:  http.MethodPost,
				Path:    "/stt",
				Handler: speechToTextHandler(serverCtx),
			},
			{
				// 文字转语音
				Method:  http.MethodPost,
				Path:    "/tts",
				Handler: textToSpeechHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/speech"),
	)
}
