// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type BaseResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type SpeechToTextRequest struct {
	AudioData  string `form:"audio_data,optional"` // base64音频数据
	Language   string `form:"language,optional,default=zh-CN"`
	Format     string `form:"format,optional,default=wav"`
	SampleRate int    `form:"sample_rate,optional,default=16000"`
}

type SpeechToTextResponse struct {
	Text       string  `json:"text"`
	Confidence float64 `json:"confidence"`
	Duration   float64 `json:"duration"`
}

type TextToSpeechRequest struct {
	Text          string        `json:"text"`
	CharacterID   int64         `json:"character_id,optional"`
	VoiceSettings VoiceSettings `json:"voice_settings,optional"`
	Format        string        `json:"format,optional,default=mp3"`
}

type TextToSpeechResponse struct {
	AudioURL string  `json:"audio_url"`
	Duration float64 `json:"duration"`
	Size     int64   `json:"size"`
}

type VoiceSettings struct {
	Rate   float64 `json:"rate,optional,default=1.0"`
	Pitch  float64 `json:"pitch,optional,default=1.0"`
	Volume float64 `json:"volume,optional,default=0.8"`
}
